
networks:
  wan:
    driver: bridge
    ipam:
      config:
        - subnet: ${WAN_SUBNET}
  dmz:
    driver: bridge
    ipam:
      config:
        - subnet: ${DMZ_SUBNET}
  vlan1:
    driver: bridge
    ipam:
      config:
      - subnet: ${VLAN1_SUBNET}