services:
  client:
    container_name: client
    build:
      context: ./client
    networks:
      wan:
        ipv4_address: ${IP_CLIENT}
    privileged: true
    command: sh -c "ip route del default && ip route add default via ${IP_FIREWALL_WAN} && exec sleep infinity"
    extra_hosts:
      - "webserver:${IP_WEBSERVER}"
      - "dnsserver:${IP_DNSSERVER}"
      - "database:${IP_DATABASE}"
    dns:
      - ${IP_DNSSERVER}
    depends_on:
      - dns-server

  firewall:
    container_name: firewall
    build:
      context: ./firewall
    networks:
      wan:
        ipv4_address: ${IP_FIREWALL_WAN}
      dmz:
        ipv4_address: ${IP_FIREWALL_DMZ}
      vlan1:
        ipv4_address: ${IP_FIREWALL_VLAN1}
    cap_add:
      - NET_ADMIN
    command: sh -c "echo '1' > /proc/sys/net/ipv4/ip_forward && exec sleep infinity"
    privileged: true

  server:
    container_name: webserver
    build:
      context: ./webserver
    networks:
      dmz:
        ipv4_address: ${IP_WEBSERVER}
    command: sh -c "ip route del default && ip route add default via ${IP_FIREWALL_DMZ} && exec sleep infinity"
    entrypoint: ["sh", "-c", "service php7.4-fpm start && nginx -g 'daemon off;'"]
    privileged: true
    extra_hosts:
      - "client:${IP_FIREWALL_DMZ}"
    depends_on:
      - firewall

  database:
    container_name: database
    build:
      context: ./database
    networks:
      vlan1:
        ipv4_address: ${IP_DATABASE}
    user: root
    command: sh -c "
      ip route del default && ip route add default via ${IP_FIREWALL_VLAN1} &&
      gosu mysql mysqld & sleep 10 &&
      mysql -e \"CREATE USER 'sad'@'%' IDENTIFIED BY 'cibersad';\" &&
      mysql -e \"GRANT ALL PRIVILEGES ON *.* TO 'sad'@'%';\" &&
      mysql -e \"FLUSH PRIVILEGES;\" &&
      wait"
    privileged: true

  dns-server:
    image: andyshinn/dnsmasq:2.78
    container_name: dnsserver
    networks:
      dmz:
        ipv4_address: ${IP_DNSSERVER}
    environment:
      - DNSMASQ_LISTEN=0.0.0.0
      - DNSMASQ_NO_DHCP=1
    privileged: true
    command: >
      sh -c "ip route del default && ip route add default via ${IP_FIREWALL_DMZ} && exec sleep infinity"
    entrypoint: ["/bin/sh", "-c", "ip route del default && ip route add default via ${IP_FIREWALL_DMZ} && /usr/sbin/dnsmasq --no-daemon --address=/example.com/127.0.0.1"]


